version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - minio-data:/data

  streamlit:
      build:
        context: ../airflow/app
      container_name: streamlit_app
      ports:
        - "8501:8501"
      environment:
        - MINIO_ENDPOINT=http://minio:9000
        - MINIO_BUCKET=airflow-data
        - MINIO_ACCESS_KEY=minioadmin
        - MINIO_SECRET_KEY=minioadmin
      volumes:
        - ../airflow/app:/app
      command: streamlit run dashboard_netflix.py --server.address=0.0.0.0

  airflow-webserver:
    image: apache/airflow:2.10.3
    depends_on:
      - postgres
    environment:
      - LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES}
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
      - ../airflow/logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    entrypoint: >
      bash -c "
        airflow db upgrade &&
        airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com 2>/dev/null || true &&
        exec airflow webserver
      "
    env_file:
      - .env


  airflow-scheduler:
    image: apache/airflow:2.10.3
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
      - ../airflow/logs:/opt/airflow/logs
    entrypoint: ["bash","-c","airflow scheduler"]
    env_file:
      - .env


  airflow-logs:
    image: apache/airflow:2.10.3
    command: airflow serve-logs
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8793:8793"
    volumes:
      - ../airflow/logs:/opt/airflow/logs
    env_file:
      - .env


  # metabase:
  #   image: metabase/metabase:v0.49.5
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     MB_DB_FILE: /metabase-data/metabase.db
  #   volumes:
  #     - metabase-data:/metabase-data   # ✅ adiciona persistência do Metabase

volumes:
  postgres-data:
  minio-data:
  metabase-data:
